input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [logger_name] =~ "dev.enes" {
    mutate { add_tag => ["n11_app"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "n11-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
