apiVersion: v1
kind: ConfigMap
metadata:
  name: n11-config
data:
  SPRING_PROFILES_ACTIVE: prod
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: http://tempo:4318/v1/traces
  ISSUER_URI: http://keycloak:8180/realms/n11
