apiVersion: v1
kind: Secret
metadata:
  name: n11-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
  KEYCLOAK_DB_USER: keycloak
  KEYCLOAK_DB_PASSWORD: keycloak
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
