spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/paymentdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/n11

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

iyzico:
  api-key: "sandbox-UoxwAHg6yc4a6SpYSUMnzqxnfPvWJcI7"
  secret-key: "sandbox-Cpra7Q9zcZwMHPcD2gEmzWLnySrdttNl"
  base-url: https://sandbox-api.iyzipay.com

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
    instances:
      iyzicoCircuitBreaker:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2s
    instances:
      iyzicoRetry:
        baseConfig: default
