spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/productdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  elasticsearch:
    uris: http://localhost:9200
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/n11
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

keycloak:
  admin:
    server-url: http://localhost:8180
    realm: n11
    master-realm: master
    admin-username: admin
    admin-password: admin
    client-id: admin-cli

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
